# Site settings
title: Omar Saucedo 
email: saucedo.10@osu.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a postdoctoral associate in the Mathematical Biosciences Institute at The Ohio State University.
   
# baseurl: "/" # the subpath of your site, e.g. /blog/
#url: "https://jabranham.com" # the base hostname & protocol for your site
#twitter_username: JAlexBranham
#github_username:  jabranham
#permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
